//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class abwesende
    {
        public int abwesenheits_id { get; set; }
        public int lehrgangsinhalts_id { get; set; }
        public int teilnehmer_id { get; set; }
        public Nullable<System.TimeSpan> abwesend_seit { get; set; }
        public Nullable<System.TimeSpan> abwesend_bis { get; set; }
        public Nullable<bool> abwesend_ganztägig { get; set; }
        public string grund { get; set; }
    
        public virtual lehrgangsinhalte lehrgangsinhalte { get; set; }
        public virtual teilnehmer teilnehmer { get; set; }
    }
}
