//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class abwesende
    {
        public int abwesenheits_id { get; set; }
        public int lehrgangsinhalts_id { get; set; }
        public int teilnehmer_id { get; set; }
        public Nullable<System.DateTime> abwesend_seit { get; set; }
        public Nullable<System.DateTime> abwesend_bis { get; set; }
        public Nullable<bool> abwesend_ganztägig { get; set; }
        public string grund { get; set; }
    
        public virtual lehrgangsinhalte lehrgangsinhalte { get; set; }
        public virtual teilnehmer teilnehmer { get; set; }
    }
}
