//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class classlog : DbContext
    {
        public classlog()
            : base("name=classlog")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abwesende> abwesende { get; set; }
        public DbSet<lehrgang> lehrgang { get; set; }
        public DbSet<lehrgangsinhalte> lehrgangsinhalte { get; set; }
        public DbSet<standorte> standorte { get; set; }
        public DbSet<teilnehmer> teilnehmer { get; set; }
        public DbSet<themen> themen { get; set; }
        public DbSet<trainer> trainer { get; set; }
    }
}
