//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class classlog : DbContext
    {
        public classlog()
            : base("name=classlog")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abwesende> abwesende { get; set; }
        public virtual DbSet<lehrgang> lehrgang { get; set; }
        public virtual DbSet<lehrgang_teilnehmer> lehrgang_teilnehmer { get; set; }
        public virtual DbSet<lehrgang_trainer> lehrgang_trainer { get; set; }
        public virtual DbSet<lehrgangsinhalte> lehrgangsinhalte { get; set; }
        public virtual DbSet<lehrgangsinhalte_themen> lehrgangsinhalte_themen { get; set; }
        public virtual DbSet<standorte> standorte { get; set; }
        public virtual DbSet<teilnehmer> teilnehmer { get; set; }
        public virtual DbSet<themen> themen { get; set; }
        public virtual DbSet<trainer> trainer { get; set; }
    }
}
