//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClasslogEntities : DbContext
    {
        public ClasslogEntities()
            : base("name=ClasslogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abwesende> abwesende { get; set; }
        public DbSet<lehrgang> lehrgang { get; set; }
        public DbSet<lehrgangsinhalte> lehrgangsinhalte { get; set; }
        public DbSet<standorte> standorte { get; set; }
        public DbSet<teilnehmer> teilnehmer { get; set; }
        public DbSet<themen> themen { get; set; }
        public DbSet<trainer> trainer { get; set; }
    }
}
