//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class classlog : DbContext
    {
        public classlog()
            : base("name=classlog")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abwesende> abwesendes { get; set; }
        public virtual DbSet<lehrgang> lehrgangs { get; set; }
        public virtual DbSet<lehrgang_teilnehmer> lehrgang_teilnehmer { get; set; }
        public virtual DbSet<lehrgang_trainer> lehrgang_trainer { get; set; }
        public virtual DbSet<lehrgangsinhalte> lehrgangsinhaltes { get; set; }
        public virtual DbSet<lehrgangsinhalte_themen> lehrgangsinhalte_themen { get; set; }
        public virtual DbSet<standorte> standortes { get; set; }
        public virtual DbSet<teilnehmer> teilnehmers { get; set; }
        public virtual DbSet<theman> themen { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
    }
}
