//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lehrgang_trainer
    {
        public int lehrgangs_id { get; set; }
        public int trainer_id { get; set; }
        public int lehrgang_trainer_id { get; set; }
    
        public virtual lehrgang lehrgang { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
