//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lehrgangsinhalte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lehrgangsinhalte()
        {
            this.abwesendes = new HashSet<abwesende>();
            this.lehrgangsinhalte_themen = new HashSet<lehrgangsinhalte_themen>();
        }
    
        public int lehrgangsinhalts_id { get; set; }
        public int lehrgangs_id { get; set; }
        public int trainer_id { get; set; }
        public System.DateTime date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abwesende> abwesendes { get; set; }
        public virtual lehrgang lehrgang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lehrgangsinhalte_themen> lehrgangsinhalte_themen { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
