//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lehrgangsinhalte
    {
        public lehrgangsinhalte()
        {
            this.abwesende = new HashSet<abwesende>();
            this.themen = new HashSet<themen>();
        }
    
        public int lehrgangsinhalts_id { get; set; }
        public int lehrgangs_id { get; set; }
        public int trainer_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ICollection<abwesende> abwesende { get; set; }
        public virtual lehrgang lehrgang { get; set; }
        public virtual trainer trainer { get; set; }
        public virtual ICollection<themen> themen { get; set; }
    }
}
