//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lehrgangsinhalte
    {
        public lehrgangsinhalte()
        {
            this.abwesende = new HashSet<abwesende>();
            this.themen = new HashSet<themen>();
        }
    
        public int lehrgangsinhalts_id { get; set; }
        public int lehrgangs_id { get; set; }
        public int trainer_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ICollection<abwesende> abwesende { get; set; }
        public virtual lehrgang lehrgang { get; set; }
        public virtual trainer trainer { get; set; }
        public virtual ICollection<themen> themen { get; set; }
    }
}
