//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lehrgang
    {
        public lehrgang()
        {
            this.lehrgangsinhalte = new HashSet<lehrgangsinhalte>();
            this.teilnehmer = new HashSet<teilnehmer>();
            this.trainer = new HashSet<trainer>();
        }
    
        public int lehrgangs_id { get; set; }
        public Nullable<System.DateTime> beginn { get; set; }
        public Nullable<System.DateTime> ende { get; set; }
        public int standort_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<lehrgangsinhalte> lehrgangsinhalte { get; set; }
        public virtual standorte standorte { get; set; }
        public virtual ICollection<teilnehmer> teilnehmer { get; set; }
        public virtual ICollection<trainer> trainer { get; set; }
    }
}
