//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lehrgang_teilnehmer
    {
        public int lehrgangs_id { get; set; }
        public int teilnehmer_id { get; set; }
        public int lehrgang_teilnehmer_id { get; set; }
    
        public virtual lehrgang lehrgang { get; set; }
        public virtual teilnehmer teilnehmer { get; set; }
    }
}
