//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class standorte
    {
        public standorte()
        {
            this.lehrgang = new HashSet<lehrgang>();
        }
    
        public int standort_id { get; set; }
        public string straße { get; set; }
        public string ort { get; set; }
        public string plz { get; set; }
    
        public virtual ICollection<lehrgang> lehrgang { get; set; }
    }
}
