//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class standorte
    {
        public standorte()
        {
            this.lehrgang = new HashSet<lehrgang>();
        }
    
        public int standort_id { get; set; }
        public string straße { get; set; }
        public string ort { get; set; }
        public string plz { get; set; }
    
        public virtual ICollection<lehrgang> lehrgang { get; set; }
    }
}
