//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class teilnehmer
    {
        public teilnehmer()
        {
            this.abwesende = new HashSet<abwesende>();
            this.lehrgang = new HashSet<lehrgang>();
        }
    
        public int teilnehmer_id { get; set; }
        public string nachname { get; set; }
        public string vorname { get; set; }
    
        public virtual ICollection<abwesende> abwesende { get; set; }
        public virtual ICollection<lehrgang> lehrgang { get; set; }
    }
}
