//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class teilnehmer
    {
        public teilnehmer()
        {
            this.abwesende = new HashSet<abwesende>();
            this.lehrgang = new HashSet<lehrgang>();
        }
    
        public int teilnehmer_id { get; set; }
        public string nachname { get; set; }
        public string vorname { get; set; }
    
        public virtual ICollection<abwesende> abwesende { get; set; }
        public virtual ICollection<lehrgang> lehrgang { get; set; }
    }
}
