//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class themen
    {
        public themen()
        {
            this.lehrgangsinhalte = new HashSet<lehrgangsinhalte>();
        }
    
        public int themen_id { get; set; }
        public string titel { get; set; }
        public string beschreibung { get; set; }
    
        public virtual ICollection<lehrgangsinhalte> lehrgangsinhalte { get; set; }
    }
}
