//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class themen
    {
        public themen()
        {
            this.lehrgangsinhalte = new HashSet<lehrgangsinhalte>();
        }
    
        public int themen_id { get; set; }
        public string titel { get; set; }
        public string beschreibung { get; set; }
    
        public virtual ICollection<lehrgangsinhalte> lehrgangsinhalte { get; set; }
    }
}
