//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalesKlassenbuch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainer
    {
        public trainer()
        {
            this.lehrgangsinhalte = new HashSet<lehrgangsinhalte>();
            this.lehrgang = new HashSet<lehrgang>();
        }
    
        public int trainer_id { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
    
        public virtual ICollection<lehrgangsinhalte> lehrgangsinhalte { get; set; }
        public virtual ICollection<lehrgang> lehrgang { get; set; }
    }
}
